### ISSUE TITLE
snap to grid

### ISSUE THREAD

**Issue by kfriedrichs** [clp-research/golmi#12]
The model's config already has the snap_to_grid option, but the functionality is not yet implemented.
- after a continuous movement is completed, a moved object should 'jump' to the nearest grid square
- no changes need to be made for rotate and grid because these options are implemented to only use full block steps anyway
- the function should of course only be active if snap_to_grid in the configuration is set to true

**Comment by phisad** [comment]
meant is the "visible" grid on the ui

**Comment by sebag90** [comment]
implementation in [pending pull request](https://github.com/clp-research/golmi/pull/22)
