### ISSUE TITLE
fix overlap bug

### ISSUE THREAD

**Issue by kfriedrichs** [clp-research/golmi#13]
**Bug description**: In the demo interface, when picking up the F piece, it can be moved to overlap with the top half block of the I.

At the same time, we could reduce the piece size, i.e. not put all objects into 5x5 matrices but use variable (square) matrix sizes. For example, many Pentomino objects like F or T would fit into a 3x3 matrix.

**Comment by kfriedrichs** [comment]
Need to test whether this bug persists in the grid version of Golmi

**Comment by sebag90** [comment]
The grid version of Golmi seems to resolve the issue, we can close it (or restrict it the pento fractions) after merging [this request](https://github.com/clp-research/golmi/pull/19)
