### ISSUE TITLE
write (model) unit tests

### ISSUE THREAD

**Issue by kfriedrichs** [clp-research/golmi#14]
The original unit tests for the model have not yet been updated to the websockets architecture. The old tests have been moved [here](https://github.com/clp-research/golmi/blob/master/app/test.py) and should be updated and possibly extended to new functionality.

**Comment by sebag90** [comment]
tests were moved to directory tests/ and can be run from the main directory (golmi/) with:
`python -m unittest` to run them all
`python -m unittest -k test_socketio` or `python -m unittest -k test_flask_endpoints` to run them singularly
