### ISSUE TITLE
Update PentoGenerator class

### ISSUE THREAD

**Issue by kfriedrichs** [clp-research/golmi#15]
The [PentoGenerator](https://github.com/clp-research/golmi/blob/master/app/static/js/PentoGenerator.js) class need to be
adapted to the Websockets architecture.

**Comment by sebag90** [comment]
the generator has been implemented as a [module](https://github.com/clp-research/golmi/blob/taget_block/model/generator.py) of the model. It is also capable of restricting the spawning areas of objects and targets independently on the board (objects are generated on the top, targets on the bottom). not merged yet to main

**Comment by sebag90** [comment]
after merging [this request](https://github.com/clp-research/golmi/pull/19) we can close this issue
