### ISSUE TITLE
step size logic

### ISSUE THREAD

**Issue by janagoetze** [clp-research/golmi#20]
Unfortunately, we still haven't got the logic right with the step size.

When the stepsize is `1`, we get a ZeroDivisionError in 2 places:
- https://github.com/clp-research/golmi/blob/07898ff4c0c7b1259c7ebde368a4723df9fb8bcf/model/config.py#L38
- https://github.com/clp-research/golmi/blob/07898ff4c0c7b1259c7ebde368a4723df9fb8bcf/model/grid.py#L83

Both for the reason that `1 % 1` evaluates to `0`. The first one is easy to fix but for the second one, I'm not sure why step is set to `1 % 1`

Solution suggestion for the first one:
```
if ( move_step != 1
    and ( (1/(move_step % 1)).is_integer()
              or isinstance(move_step, int))
    )
```
⬆️ actually, this is not fully correct either, I think. need to rethink.

**Comment by janagoetze** [comment]
also, let's rename `self.heigth` to `self.height`

**Comment by sebag90** [comment]
I think I solved it by checking with:
``` 
if move_step != 1:
            if (move_step == 0 or (not (1/(move_step % 1)).is_integer() and
                    not isinstance(move_step, int))):
```
I'm pretty sure* this should cover all cases. I also added a similar condition on the grid side.

I'm using```move_step = move_step % 1 ``` to reduce float move_steps higher than one to the equivalent 0.something (we need the same grid and calculations for 0.5, 1.5, 2.5 etc...)

* sureness not guaranteed

**Comment by sebag90** [comment]
should be fixed now with [this commit](https://github.com/clp-research/golmi/commit/d3aad540d534c221603d985d1164be3969705425)
