### ISSUE TITLE
load_config fails when type_config is missing even on partial updates

### ISSUE THREAD

**Issue by phisad** [clp-research/golmi#24]
When I have initially loaded a config and then want to update only part of it using `load_config` again, I'm still required to provide `type_config`, because `Config.from_dict` is called in this process (but maybe shouldnt). 

I actually only want to set other parameters, for example:

```
	const CONFIG = {
		"move_step": 0.5,
		"width": 40,
		"height": 40
	}
```

We might want to have an `update_config` event for the backend.

**Comment by phisad** [comment]
Another option would be to actually not permit partial updates on the config.

**Comment by kfriedrichs** [comment]
This is fixed in the `fix_refactor_config` branch, will merge once PR #32 is accepted as there might be some conflicts to resolve.
