### ISSUE TITLE
test_with_color_fails_when_ambiguous_color failing

### ISSUE THREAD

**Issue by kfriedrichs** [clp-research/golmi#37]
[`test_generators.test_with_color_fails_when_ambiguous_color`](https://github.com/clp-research/golmi/blob/2a4f136b27941ca103fc50bddeb1e82e60c8794f/tests/test_generators.py#L101) fails on the main branch.

While we're at it, maybe we could rename the module to something else, because the name suggests the model.generator class is tested here. Maybe test_pentomino_functions?

**Comment by phisad** [comment]
Good idea "test_pentomino" should be sufficient.
