### ISSUE TITLE
Log view

### ISSUE THREAD

**Issue by kfriedrichs** [clp-research/golmi#6]
Views could be used for logging, since they get all state updates from the model they are subscribed to.
An implementation could be a View API running on our server during remote experiments. During setup, the client-side code subscribes the model to the log view. The view API then receives updates and saves them with timestamps. Also, some identifier would be needed to differentiate between participants.

**Comment by kfriedrichs** [comment]
In analogy to the Pento-Fractions project, the logs could be used to later create a 'replay' of some movements

**Comment by phisad** [comment]
Is this resolved? Or is there an existing PR?

**Comment by kfriedrichs** [comment]
Gah, this has been on my todo list forever. I wrote a lot of additional LogView code for pento_fractions and need to sort through it and decide what might be reusable. Promise I'll take care of it!
